export const PointLog = {
  message: "SUCCESS",
  data: {
    details: [
      {
        user_name: "이연우",
        id: 1,
        cause: "예측 성공!",
        event: "농구 경기",
        point: 1000,
        created_at: "2024-04-30T00:08:44",
        is_betting: true,
        user_id: 1,
        game_id: 1,
        team_id: 1,
      },
      {
        user_name: "이연우",
        id: 5,
        cause: "예측 참가",
        event: "농구 경기",
        point: -500,
        created_at: "2024-04-30T00:13:57",
        is_betting: null,
        user_id: 1,
        game_id: 1,
        team_id: 1,
      },
      {
        user_name: "이연우",
        id: 6,
        cause: "예측 참여",
        event: "족구 경기",
        point: -500,
        created_at: "2024-04-30T00:14:35",
        is_betting: null,
        user_id: 1,
        game_id: 1,
        team_id: 1,
      },
      {
        user_name: "이연우",
        id: 7,
        cause: "예측 성공!",
        event: "농구 경기",
        point: 500,
        created_at: "2024-04-30T00:17:12",
        is_betting: true,
        user_id: 1,
        game_id: 1,
        team_id: 1,
      },
      {
        user_name: "이연우",
        id: 8,
        cause: "예측 성공!",
        event: "농구 경기",
        point: 500,
        created_at: "2024-04-30T00:17:43",
        is_betting: true,
        user_id: 1,
        game_id: 1,
        team_id: 1,
      },
      {
        user_name: "이연우",
        id: 9,
        cause: "예측 성공!",
        event: "농구 경기",
        point: 500,
        created_at: "2024-04-30T00:17:44",
        is_betting: true,
        user_id: 1,
        game_id: 1,
        team_id: 1,
      },
      {
        user_name: "이연우",
        id: 10,
        cause: "예측 성공!",
        event: "농구 경기",
        point: 500,
        created_at: "2024-04-30T00:17:59",
        is_betting: true,
        user_id: 1,
        game_id: 1,
        team_id: 1,
      },
      {
        user_name: "이연우",
        id: 11,
        cause: "예측 참여",
        event: "배구 경기",
        point: -500,
        created_at: "2024-04-30T00:19:51",
        is_betting: true,
        user_id: 1,
        game_id: 1,
        team_id: 1,
      },
      {
        user_name: "이연우",
        id: 12,
        cause: "예측 참여",
        event: "농구 경기",
        point: -500,
        created_at: "2024-04-30T00:22:04",
        is_betting: true,
        user_id: 1,
        game_id: 1,
        team_id: 1,
      },
      {
        user_name: "이연우",
        id: 13,
        cause: "초기 포인트 지급",
        event: "학생회",
        point: -2500,
        created_at: "2024-04-30T00:33:29",
        is_betting: true,
        user_id: 1,
        game_id: 1,
        team_id: 1,
      },
    ],
  },
};
