export const PointLog = {
  message: "SUCCESS",
  data: {
    details: [
      {
        user_name: "이연우",
        id: 1,
        point: 1000,
        created_at: "2024-04-30T00:08:44",
        is_betting: true,
        user_id: 1,
        game_id: 1,
        team_id: 1,
      },
      {
        user_name: "이연우",
        id: 5,
        point: 500,
        created_at: "2024-04-30T00:13:57",
        is_betting: null,
        user_id: 1,
        game_id: 1,
        team_id: 1,
      },
      {
        user_name: "이연우",
        id: 6,
        point: 500,
        created_at: "2024-04-30T00:14:35",
        is_betting: null,
        user_id: 1,
        game_id: 1,
        team_id: 1,
      },
      {
        user_name: "이연우",
        id: 7,
        point: 500,
        created_at: "2024-04-30T00:17:12",
        is_betting: true,
        user_id: 1,
        game_id: 1,
        team_id: 1,
      },
      {
        user_name: "이연우",
        id: 8,
        point: 500,
        created_at: "2024-04-30T00:17:43",
        is_betting: true,
        user_id: 1,
        game_id: 1,
        team_id: 1,
      },
    ],
  },
};
